### ISSUE TITLE
Plugin deploys only the first application configured in manifest.yml

### ISSUE THREAD

**Issue by buchen** [ActiveState/cloudfoundry-jenkins#1]
One can define multiple applications in a manifest.yml file.
Quickly glancing over the ManfestReader, that class also understands that.
However, only the first application is deployed because there seems to be only one DeploymentInfo.

Any plans to change that?

**Comment by WGautier** [comment]
Related to: https://issues.jenkins-ci.org/browse/JENKINS-26546

Fixed by 07bc759 and available in v1.1.

Support for [configuration that affects all applications](http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#minimize-duplication) is not implemented yet, but may be in the future.
