### ISSUE TITLE
Plugin needs to handle the stack property

### ISSUE THREAD

**Issue by drissamri** [ActiveState/cloudfoundry-jenkins#6]
The [lucid64 stack](https://docs.cloudfoundry.org/concepts/stacks.html) has been deprecated and removed for most buildpacks. The default on the commandline is still lucid64 though. 

```
 It looks like you're deploying on a stack (currently set to *lucid64*) that's not supported by this buildpack.
```

The stack entry manifest.yml is not being parsed/used.

**Comment by jsloyer** [comment]
Submitted a PR https://github.com/jenkinsci/cloudfoundry/pull/8

**Comment by drissamri** [comment]
Again, great work @jsloyer. Thank you for the quick fix. Hope it will in the official plugin asap.

**Comment by WGautier** [comment]
jenkinsci#8 is merged now, closing.
